export interface MouselabConfig {
  ANIMATION_SPEED: number;
  SIZE: number;
  EDGE_WIDTH: number;
  HOVER_EDGE_WIDTH: number;
  ARROW_HEAD_SIZE: number;
  BRANCH_LABEL_FONT_SIZE: number;
  ACTION_COLORS: string[];
  DEFAULT_EDGE_COLOR: string;
  TRAIL_COLOR: string;
  TRAIL_WIDTH: number;
  STEM_COLOR: string;
  STEM_WIDTH: number;
  NODE_INTERACTION_MODE: "hover" | "click" | "always" | "never" | null;
  EDGE_INTERACTION_MODE: "hover" | "click" | "always" | "never" | null;
  DEBUG_SHOW_VALUES: boolean;
  NODE_RADIUS_RATIO: number;
  NODE_FONT_SIZE_RATIO: number;
  NODE_LABEL_PADDING_X: number;
  NODE_LABEL_PADDING_Y: number;
  NODE_LINE_HEIGHT_RATIO: number;
  NODE_LABEL_BG_RADIUS: number;
  NODE_LABEL_BG_STROKE: string;
  NODE_LABEL_TEXT_FILL: string;
  NODE_REWARD_TEXT_FILL: string;
  NODE_DEFAULT_FILL: string;
  DEFAULT_EDGE_SPACING: number;
  EDGE_LABEL_OFFSET_RATIO: number;
  BRANCH_ARROW_POSITION_RATIO: number;
  BRANCH_RADIUS_GAP: number;
  BRANCH_LABEL_PADDING: number;
  BRANCH_LABEL_INDENT: number;
  BRANCH_GROUP_LABEL_SIZE_DELTA: number;
  BRANCH_RECT_PADDING: number;
  BRANCH_RECT_OFFSET_X: number;
  BRANCH_LABEL_BG_FILL: string;
  BRANCH_LABEL_BG_STROKE: string;
  PLAYER_SCALE_DEFAULT: number;
  TRAIL_OFFSET: number;
}

export const CONFIG: MouselabConfig = {
  ANIMATION_SPEED: 0.5,
  SIZE: 120,
  EDGE_WIDTH: 4,
  HOVER_EDGE_WIDTH: 6,
  ARROW_HEAD_SIZE: 10,
  BRANCH_LABEL_FONT_SIZE: 12,
  ACTION_COLORS: ["#2196F3", "#F44336", "#4CAF50", "#FF9800"],
  DEFAULT_EDGE_COLOR: "#888",
  TRAIL_COLOR: "#1565C0",
  TRAIL_WIDTH: 5,
  STEM_COLOR: "#888",
  STEM_WIDTH: 4,
  NODE_INTERACTION_MODE: null,
  EDGE_INTERACTION_MODE: null,
  DEBUG_SHOW_VALUES: false,
  NODE_RADIUS_RATIO: 0.25,
  NODE_FONT_SIZE_RATIO: 1 / 6,
  NODE_LABEL_PADDING_X: 8,
  NODE_LABEL_PADDING_Y: 4,
  NODE_LINE_HEIGHT_RATIO: 0.2,
  NODE_LABEL_BG_RADIUS: 4,
  NODE_LABEL_BG_STROKE: "#444",
  NODE_LABEL_TEXT_FILL: "#222",
  NODE_REWARD_TEXT_FILL: "#888",
  NODE_DEFAULT_FILL: "#bbb",
  DEFAULT_EDGE_SPACING: 8,
  EDGE_LABEL_OFFSET_RATIO: 0.45,
  BRANCH_ARROW_POSITION_RATIO: 0.55,
  BRANCH_RADIUS_GAP: 8,
  BRANCH_LABEL_PADDING: 6,
  BRANCH_LABEL_INDENT: 10,
  BRANCH_GROUP_LABEL_SIZE_DELTA: 2,
  BRANCH_RECT_PADDING: 8,
  BRANCH_RECT_OFFSET_X: 7,
  BRANCH_LABEL_BG_FILL: "white",
  BRANCH_LABEL_BG_STROKE: "#444",
  PLAYER_SCALE_DEFAULT: 0.3,
  TRAIL_OFFSET: 7.5,
};
